spring.application.name=iWindoor Backend

# Veritaban? Ba?lant? Ayarlar?
spring.datasource.url=jdbc:postgresql://localhost:5432/windoor_db
spring.datasource.username=admin
spring.datasource.password=123456789

# JPA / Hibernate Ayarlar?
# update: Entity'de yapt???n de?i?ikli?i veritaban? tablosuna yans?t?r (veriyi silmez).
# create-drop: Uygulama her kapand???nda her ?eyi siler (Test için iyidir ama dikkat!).
spring.jpa.hibernate.ddl-auto=update

# SQL Sorgular?n? Gösterme (Geli?tirme yaparken konsolda SQL'leri görmek hayat kurtar?r)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect (Opsiyonel ama iyidir)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect